import { AccountFactory } from '@core/account-factory';
import { AccountGroupFactory } from '@core/account-group-factory';
import { AccountGroupManager } from '@core/account-group-manager';
import { AccountGroupStore } from '@core/account-group-store';
import { AppDatabase } from '@core/app-database';
import { CreditCardFactory } from '@core/credit-card-factory';
import { ProfileFactory } from '@core/profile-factory';
import { ProfileGroupFactory } from '@core/profile-group-factory';
import { ProfileGroupManager } from '@core/profile-group-manager';
import { ProfileGroupStore } from '@core/profile-group-store';
import { ProxyFactory } from '@core/proxy-factory';
import { ProxyGroupFactory } from '@core/proxy-group-factory';
import { ProxyGroupStore } from '@core/proxy-group-store';
import { Settings } from '@core/settings';
import { SettingsManager } from '@core/settings-manager';
import { SettingsStore } from '@core/settings-store';
import { TaskFactory } from '@core/task-factory';
import { TaskGroupFactory } from '@core/task-group-factory';
import { TaskGroupStore } from '@core/task-group-store';
import { app, BrowserWindow, ipcMain, session } from 'electron';
import hash from 'object-hash';
import si from 'systeminformation';
import { ACCESS_GRANTED, CAPTHA_WINDOW_CLOSED, CAPTHA_WINDOW_OPEN, GET_SYSTEM_ID, SET_PROXY_CAPTCHA_WINDOW, STORE_KEY } from './common/Constants';
import { CaptchaType, STORES, StoreType } from './constants/stores';
import { captchaWindowManager } from './core/captcha-window/CaptchaWindowManager';
import { debug } from './core/log';
import { ProxyGroupManager } from './core/proxy-group-manager';
import { TaskGroupManager } from './core/task-group-manager';
import { Proxy } from './interfaces/OtherInterfaces';
import UserAgentProvider from './services/user-agent-provider';

const log = debug.extend('main');
/* eslint-disable @typescript-eslint/no-unused-vars */
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const LICENSE_WINDOW_WEBPACK_ENTRY: string;
declare const GOOGLE_CAPTCHA_WINDOW_WEBPACK_ENTRY: string;
declare const PX_CAPTCHA_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow;

console.log('WEBPACK ENTRY', MAIN_WINDOW_WEBPACK_ENTRY);

const disableSpellcheckerDownload = () => {
    session.defaultSession.setSpellCheckerDictionaryDownloadURL('https://00.00/');
};

const getSystemUniqueID = async (): Promise<string> => {
    try {
        const SYSTEM_ID = await si.system();
        const HASHED_DATA = await hash(SYSTEM_ID);
        return HASHED_DATA;
    } catch (error) {
        throw new Error('Could not fetch system information');
    }
};

const createWindow = () => {
    mainWindow = new BrowserWindow({
        width: 1700,
        height: 830,
        minWidth: 960,
        minHeight: 600,

        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    mainWindow.loadURL(LICENSE_WINDOW_WEBPACK_ENTRY);

    if (process.env.NODE_ENV === 'development') {
        mainWindow.webContents.openDevTools();
    }

    mainWindow.setMenuBarVisibility(false);
    mainWindow.setAutoHideMenuBar(true);

    // if main windows is close, close all other captcha window
    mainWindow.on('close', () => {
        captchaWindowManager.closeAll();
    });
};

let appDatabase: AppDatabase;
let profileGroupManager: ProfileGroupManager;
let accountGroupManager: AccountGroupManager;
let proxySetManager: ProxyGroupManager;
let taskGroupManager: TaskGroupManager;
let settingsManager: SettingsManager;
let settingsStore: SettingsStore;
let profileGroupStore: ProfileGroupStore;
let proxyGroupStore: ProxyGroupStore;
let taskGroupStore: TaskGroupStore;
let accountGroupStore: AccountGroupStore;

app.whenReady().then(async () => {
    await session.defaultSession.loadExtension('/home/wail/.config/google-chrome/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi/4.22.0_0');

    disableSpellcheckerDownload();
    createWindow();

    log('Initiatilising app');

    appDatabase = new AppDatabase();

    const settings = new Settings();
    settingsStore = new SettingsStore(appDatabase, settings);

    const creditCardFactory = new CreditCardFactory();
    const profileFactory = new ProfileFactory(creditCardFactory);
    const profileGroupFactory = new ProfileGroupFactory();
    profileGroupStore = new ProfileGroupStore(appDatabase, profileGroupFactory, profileFactory);

    const proxyGroupFactory = new ProxyGroupFactory();
    const proxyFactory = new ProxyFactory();
    proxyGroupStore = new ProxyGroupStore(appDatabase, proxyFactory, proxyGroupFactory);

    const taskGroupFactory = new TaskGroupFactory();
    const taskFactory = new TaskFactory(mainWindow);
    taskGroupStore = new TaskGroupStore(appDatabase, taskGroupFactory, taskFactory);

    const accountGroupFactory = new AccountGroupFactory();
    const accountFactory = new AccountFactory(mainWindow);
    accountGroupStore = new AccountGroupStore(appDatabase, accountGroupFactory, accountFactory, taskGroupStore);

    settingsManager = new SettingsManager(settingsStore);
    proxySetManager = new ProxyGroupManager(proxyGroupStore, taskGroupStore);
    taskGroupManager = new TaskGroupManager(taskGroupStore, profileGroupStore, accountGroupStore, proxyGroupStore);
    accountGroupManager = new AccountGroupManager(accountGroupStore, settingsStore);
    profileGroupManager = new ProfileGroupManager(profileGroupStore, creditCardFactory);

    await settingsManager.ready();
    await profileGroupManager.ready();
    await proxySetManager.ready();
    await accountGroupManager.ready();
    await taskGroupManager.ready();
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// if (process.platform === 'darwin') {
//     app.dock.hide();
// }

// IPC EVENTS
ipcMain.on(ACCESS_GRANTED, () => {
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
});

app.on('window-all-closed', async () => {
    //TODO(wail) maybe not the best place to put this here
    log('Saving models to DB');
    await profileGroupStore.saveToDB();
    await proxyGroupStore.saveToDB();
    await taskGroupStore.saveToDB();
    await settingsStore.saveToDB();
    await accountGroupStore.saveToDB();

    log('models saved!');

    if (process.platform !== 'darwin') {
        app.quit();
    }
});

ipcMain.on(CAPTHA_WINDOW_OPEN, (event, store: StoreType, proxyHost: string) => {
    const currentStore = STORES[store];

    log('New captcha window open %o', store);

    const capWin = captchaWindowManager.getWindow(store);
    if (capWin) {
        // on open send the captcha
        capWin.show();
        return;
    }

    const newWin = new BrowserWindow({
        // parent: win, //dont set parent or else it will not be visible in taskbar
        width: 465 + 700,
        height: 630,
        fullscreenable: false,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    if (process.env.NODE_ENV === 'development') {
        newWin.webContents.openDevTools();
    }

    newWin.setMenuBarVisibility(false);
    newWin.setAutoHideMenuBar(true);
    newWin.webContents.setUserAgent(UserAgentProvider.randomUserAgent());
    captchaWindowManager.register(store, newWin);

    switch (currentStore.captchaType) {
        case CaptchaType.Google:
            newWin.loadURL(GOOGLE_CAPTCHA_WINDOW_WEBPACK_ENTRY);
            break;
        case CaptchaType.Px:
            newWin.loadURL(PX_CAPTCHA_WINDOW_WEBPACK_ENTRY);
            break;
    }
    newWin.on('close', (e) => {
        log('close');
        e.preventDefault();
        event.reply(CAPTHA_WINDOW_CLOSED(store));
        newWin.hide();
    });

    // When the window is initially created it wont receive the 'show' event.
    // So initially send the store key when it finishes loading.
    newWin.webContents.on('did-finish-load', () => {
        newWin.webContents.send(STORE_KEY, store, 'did finish load');
    });
});

ipcMain.on(SET_PROXY_CAPTCHA_WINDOW, (event, storeType: StoreType, proxy: Proxy) => {
    log('Setting captch window proxy with %O', proxy);
    const capWin = captchaWindowManager.getWindow(storeType);

    if (!capWin) {
        log('No captcha window found');
        return;
    }

    capWin.webContents.session.setProxy({ proxyRules: proxy.host });

    // set proxy auth
    app.on('login', (event, webContents, details, authInfo, callback) => {
        event.preventDefault();
        log('Proxy authentication required');
        callback(proxy.credential.split(':')[0], proxy.credential.split(':')[1]);
    });

    app.removeAllListeners('login');
});

ipcMain.handle(GET_SYSTEM_ID, async (event) => {
    try {
        const ID = await getSystemUniqueID();
        return ID;
    } catch (error) {
        console.log('err', error);
    }
});
