// Headers used to request https://walmart.com/ip/productname/productid
// TODO currently homepage used and product page, will check later what works best.
export const WALMART_US_PRODUCT_PAGE_HEADERS = {
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    pragma: 'no-cache',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'service-worker-navigation-preload': 'true',
    'upgrade-insecure-requests': '1',
};

export const WALMART_US_HOMEPAGE_HEADERS = {
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9',
    'cache-control': 'max-age=0',
    'sec-ch-ua': '"Chromium";v="94", "Microsoft Edge";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'service-worker-navigation-preload': 'true',
    'upgrade-insecure-requests': '1',
};

export const WALMART_US_GET_ITEM_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    calltype: 'CLIENT',
    'content-type': 'application/json',
    'is-variant-fetch': 'false',
    origin: 'https://www.walmart.com',
    referer: 'https://www.walmart.com/ip/',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'ItemById',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'query ItemById',
    'x-o-item-id': '127446742',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_MERGE_GET_CART_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'MergeAndGetCart',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation MergeAndGetCart',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_ATC_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-ch-ua': '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'updateItems',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-correlation-id': 'h5MAHCVM4PjlZAxOTKE5o8zewrMPKhkWeM_G',
    'x-o-gql-query': 'mutation updateItems',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_CREATE_DELIVERY_ADDRESS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateDeliveryAddress',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateDeliveryAddress',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_SET_FULFILLMENT_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'setFulfillment',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation setFulfillment',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};
export const WALMART_US_CREATE_CONTRACT_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateContract',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateContract',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};

export const WALMART_US_GET_TENDER_PLAN_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'getTenderPlan',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'query getTenderPlan',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};

export const WALMART_US_CREATE_CREDIT_CARD_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateCreditCard',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateCreditCard',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};
export const WALMART_US_UPDATE_TENDER_PLAN_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'updateTenderPlan',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation updateTenderPlan',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_SAVE_TENDER_PC_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'saveTenderPlanToPC',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation saveTenderPlanToPC',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_PLACE_ORDER_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-ch-ua': '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'PlaceOrder',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation PlaceOrder',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_PURCHASE_CONTRACT_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'PurchaseContract',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};

export const WALMART_CA_SESSION_HEADERS = {
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-US,en;q=0.9',
    'sec-ch-ua': '"Chromium";v="94", "Microsoft Edge";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
};

export const WALMART_CA_ADD_CART_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/en/ip/',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36',
    'wm_qos.correlation_id': '37443bb2-026-17c5404b17cb2e,37443bb2-026-17c5404b17cbe6,37443bb2-026-17c5404b17cbe6',
};

export const WALMART_CA_CHECKOUT_GUEST_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
};

export const WALMART_CA_SHIPPING_ADDRESS_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
};

export const WALMART_CA_SHIPPING_METHOD_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
};

export const WALMART_CA_CC_SUMMARY_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36',
};

export const WALMART_CA_CREDIT_CARD_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
};

export const WALMART_CA_PLACE_ORDER_HEADERS = {
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    origin: 'https://www.walmart.ca',
    pragma: 'no-cache',
    referer: 'https://www.walmart.ca/checkout',
    'sec-ch-ua': '"Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
};
