import { COMMON_HEADERS } from './Constants';

// Headers used to request https://walmart.com/ip/productname/productid
export const WALMART_US_PRODUCT_PAGE_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    pragma: 'no-cache',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'service-worker-navigation-preload': 'true',
    'upgrade-insecure-requests': '1',
};

export const WALMART_US_GET_ITEM_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    calltype: 'CLIENT',
    'content-type': 'application/json',
    'is-variant-fetch': 'false',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'ItemById',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'query ItemById',
    'x-o-item-id': '127446742',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_MERGE_GET_CART_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'MergeAndGetCart',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation MergeAndGetCart',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_ATC_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-ch-ua': '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'updateItems',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-correlation-id': 'h5MAHCVM4PjlZAxOTKE5o8zewrMPKhkWeM_G',
    'x-o-gql-query': 'mutation updateItems',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_CREATE_DELIVERY_ADDRESS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateDeliveryAddress',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateDeliveryAddress',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};

export const WALMART_US_SET_FULFILLMENT_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'setFulfillment',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation setFulfillment',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};
export const WALMART_US_CREATE_CONTRACT_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateContract',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateContract',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};

export const WALMART_US_GET_TENDER_PLAN_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'getTenderPlan',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'query getTenderPlan',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};

export const WALMART_US_CREATE_CREDIT_CARD_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'CreateCreditCard',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation CreateCreditCard',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
};
export const WALMART_US_UPDATE_TENDER_PLAN_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'updateTenderPlan',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation updateTenderPlan',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_SAVE_TENDER_PC_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'saveTenderPlanToPC',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation saveTenderPlanToPC',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_PLACE_ORDER_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/review-order',
    'sec-ch-ua': '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'PlaceOrder',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-gql-query': 'mutation PlaceOrder',
    'x-o-platform': 'rweb',
    'x-o-platform-version': 'main-95-7de933',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_PURCHASE_CONTRACT_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en-US;q=0.9,en;q=0.8,fr;q=0.7',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_mp: 'true',
    'x-apollo-operation-name': 'PurchaseContract',
    'x-enable-server-timing': '1',
    'x-latency-trace': '1',
    'x-o-ccm': 'server',
    'x-o-platform-version': 'main-95-170e1e',
    'x-o-segment': 'oaoh',
    'x-o-tp-phase': 'tp5',
};
export const WALMART_US_CHECKOUT_CART_HEADERS = {
    ...COMMON_HEADERS,
    Accept: 'application/json, text/javascript, */*; q=0.01',
    'Content-Type': 'application/json',
    Referer: 'https://www.walmart.com/checkout/',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
    'sec-ch-ua-mobile': '?0',
    WM_CVV_IN_SESSION: 'true',
    WM_VERTICAL_ID: '0',
};

export const WALMART_US_SHIPPING_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json, text/javascript, */*; q=0.01',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-CA,en;q=0.9',
    'cache-control': 'no-cache',
    'content-type': 'application/json',
    inkiru_precedence: 'false',
    origin: 'https://www.walmart.com',
    pragma: 'no-cache',
    referer: 'https://www.walmart.com/checkout/',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
    'sec-ch-ua-mobile': '?0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    wm_cvv_in_session: 'true',
    wm_vertical_id: '0',
};

export const WALMART_US_CREDIT_CARD_HEADERS = { ...WALMART_US_SHIPPING_HEADERS };

export const WALMART_US_CONFIRM_PAYMENT_HEADERS = {
    ...COMMON_HEADERS,
    accept: 'application/json, text/javascript, */*; q=0.01',
    'content-type': 'application/json',
    inkiru_precedence: 'false',
    Referer: 'https://www.walmart.com/checkout/',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
    'sec-ch-ua-mobile': '?0',
    wm_cvv_in_session: 'true',
    wm_vertical_id: '0',
};

export const WALMART_US_CHECKOUT_HEADERS = {
    ...WALMART_US_CONFIRM_PAYMENT_HEADERS,
};
